// Build: inline locale/<lang>/*.json into lib/client.js (ModuleLoader bundle).
// Run: node tools/build-client.mjs   (also via `npm run build`)
// Rule: filename (without .json) == locale namespace, EXCEPT settings.locale.json -> "settings.locale".
// Every language folder under locale/ is bundled; _policy is metadata, not a language.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const localeRoot = join(root, 'locale');

// id + native label. Order defines the language picker order.
const LANGS = [
  { id: 'ko', label: '한국어' },
  { id: 'ja', label: '日本語' },
  { id: 'zh-tw', label: '繁體中文 (台灣)' },
  { id: 'zh-hk', label: '繁體中文 (香港)' },
  { id: 'de', label: 'Deutsch' },
  { id: 'fr', label: 'Français' },
  { id: 'es', label: 'Español' },
  { id: 'pt-br', label: 'Português (Brasil)' },
  { id: 'it', label: 'Italiano' },
  { id: 'nl', label: 'Nederlands' },
  { id: 'pl', label: 'Polski' },
  { id: 'ru', label: 'Русский' },
  { id: 'uk', label: 'Українська' },
  { id: 'sv', label: 'Svenska' },
  { id: 'tr', label: 'Türkçe' },
  { id: 'id', label: 'Bahasa Indonesia' },
  { id: 'vi', label: 'Tiếng Việt' },
  { id: 'th', label: 'ไทย' },
  { id: 'hi', label: 'हिन्दी' },
  { id: 'ar', label: 'العربية' },
  { id: 'tl', label: 'Filipino' },
  { id: 'ro', label: 'Română' },
  { id: 'bn', label: 'বাংলা' },
  { id: 'ur', label: 'اردو' },
  { id: 'he', label: 'עברית' },
  { id: 'fa', label: 'فارسی' },
  { id: 'pt', label: 'Português (Portugal)' },
  { id: 'sw', label: 'Kiswahili' },
  { id: 'yo', label: 'Yorùbá' },
];

// namespace per file: "common.json" -> "common", "settings.locale.json" -> "settings.locale"
function loadLang(langId) {
  const dir = join(localeRoot, langId);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => [basename(f, '.json'), JSON.parse(readFileSync(join(dir, f), 'utf8'))])
    .sort(([a], [b]) => (a < b ? -1 : 1));
}

const perLang = new Map();
for (const { id } of LANGS) {
  const entries = loadLang(id);
  for (const [ns, dict] of entries) {
    if (typeof dict !== 'object' || dict === null || Array.isArray(dict)) {
      throw new Error(`locale/${id}/${ns}.json must be a JSON object`);
    }
    for (const [k, v] of Object.entries(dict)) {
      if (typeof v !== 'string') throw new Error(`${id}/${ns}: key "${k}" must be a string`);
      if (/[\r\n]/.test(k)) throw new Error(`${id}/${ns}: key "${k}" must not contain newlines`);
    }
  }
  perLang.set(id, entries);
  const total = entries.reduce((n, [, d]) => n + Object.keys(d).length, 0);
  if (entries.length) console.log(`${id}: ${entries.length} namespaces, ${total} keys`);
}

const present = LANGS.filter(({ id }) => perLang.get(id)?.length).map((entry) => entry);
if (!present.length) throw new Error('no language folder under locale/ has dictionaries');

// Optional subset: `node tools/build-client.mjs --langs ko,ja` bundles only the
// listed languages. Omit the flag to bundle every language folder under locale/.
const argIdx = process.argv.indexOf('--langs');
const subset = argIdx >= 0 ? process.argv[argIdx + 1] : null;
if (subset) {
  const wanted = subset.split(',').map((s) => s.trim()).filter(Boolean);
  const known = new Set(LANGS.map(({ id }) => id));
  const unknown = wanted.filter((id) => !known.has(id));
  if (unknown.length) throw new Error(`unknown language id(s): ${unknown.join(', ')}`);
  const chosen = present.filter(({ id }) => wanted.includes(id));
  if (!chosen.length) throw new Error('--langs matched no language folder under locale/');
  present.splice(0, present.length, ...chosen);
  console.log(`subset build: ${present.map(({ id }) => id).join(', ')}`);
}

const langSrc = JSON.stringify(present.map(({ id, label }) => ({ id, label })), null, 2);
const dictSrc = JSON.stringify(
  Object.fromEntries(present.map(({ id }) => [id, Object.fromEntries(perLang.get(id))])),
  null,
  2,
);

const client = `// dsh-locale-pack — browser half (generated by tools/build-client.mjs; edit locale/<lang>/*.json, then rebuild).
// Registers ${present.length} languages and their dictionaries. Missing keys fall back
// to English by the locale runtime's fallback chain, so new keys shipped by a
// DSH upgrade keep working (in English) until translated.
window.__ModuleLoader__.load({
  id: "dsh-locale-pack",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

    //#region language list (generated)
    const LANGS = ${langSrc};
    //#endregion

    //#region dictionaries (generated)
    const DICTS = ${dictSrc};
    //#endregion

    /** Required services: the locale registry owned by dsh-client-locale. */
    const inject = ["locale"];

    /**
     * Client plugin body: add every language and register its dictionaries.
     * Everything is idempotent and failure-isolated: a duplicate language
     * registration (double load) or a namespace that rejects a language must
     * not take the GUI boot down.
     * @param ctx - client root context.
     */
    function apply(ctx) {
      for (const { id, label } of LANGS) {
        ctx.effect(() => {
          try {
            ctx.locale.addLanguage({ id, label, fallback: "en" });
          } catch (error) {
            if (!/already registered/.test(String(error && error.message))) throw error;
          }
          return () => {};
        }, "locale-pack: language " + id);
      }
      for (const [lang, namespaces] of Object.entries(DICTS)) {
        for (const [ns, dict] of Object.entries(namespaces)) {
          ctx.effect(() => {
            try {
              return ctx.locale.register(ns, { [lang]: dict });
            } catch (error) {
              if (!/already has locale/.test(String(error && error.message))) throw error;
              return () => {};
            }
          }, "locale-pack: " + lang + "/" + ns);
        }
      }
    }

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
`;

writeFileSync(join(root, 'lib', 'client.js'), client, 'utf8');
const total = present.reduce((n, { id }) => n + perLang.get(id).reduce((m, [, d]) => m + Object.keys(d).length, 0), 0);
console.log(`wrote lib/client.js (${present.length} languages, ${total} keys)`);
